// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/equal

package equal

func (e *DataMonitor) Equal(a *DataMonitor) bool {
	if e.Name != a.Name {
		return false
	}

	if e.AddressType != a.AddressType {
		return false
	}

	if e.BlockAddress != a.BlockAddress {
		return false
	}

	if e.BitIndex != a.BitIndex {
		return false
	}

	if e.Scale != a.Scale {
		return false
	}

	if e.DefaultValue != a.DefaultValue {
		return false
	}

	if e.Description != a.Description {
		return false
	}

	if e.Identity != a.Identity {
		return false
	}

	if e.Tag != a.Tag {
		return false
	}

	return true
}
