// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/equal

package equal

func (e *DataMonitor) Equal(oe *DataMonitor) bool {
	if e.Name != oe.Name {
		return false
	}

	if e.AddressType != oe.AddressType {
		return false
	}

	if e.BlockAddress != oe.BlockAddress {
		return false
	}

	if e.BitIndex != oe.BitIndex {
		return false
	}

	if e.Scale != oe.Scale {
		return false
	}

	if e.DefaultValue != oe.DefaultValue {
		return false
	}

	if e.Description != oe.Description {
		return false
	}

	if e.Identity != oe.Identity {
		return false
	}

	if e.Tag != oe.Tag {
		return false
	}

	return true
}
